
version: "3.7"

services:
  atvloadly:
    image: bitxeno/atvloadly:latest
    restart: on-failure
    security_opt:
      - seccomp:unconfined
    ports:
      - "5533:80"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon:/var/run/avahi-daemon
